### ISSUE TITLE
dns-update SyntaxError

### ISSUE THREAD

**Issue by aroth-fastprotect** [aroth-arsoft/arsoft-python#1]
dns-update --server 192.168.1.1 -a 't01.example.net.=192.168.1.1/A'
Traceback (most recent call last):
  File "/usr/sbin/dns-update", line 386, in <module>
    sys.exit(app.main())
  File "/usr/sbin/dns-update", line 328, in main
    if not self._add_record(dns_update_app._split_args(args.add)):
  File "/usr/sbin/dns-update", line 76, in _add_record
    update.add(name, self.ttl, self.rrtype, payload)
  File "/usr/lib/python2.7/dist-packages/dns/update.py", line 128, in add
    self._add(False, self.authority, name, *args)
  File "/usr/lib/python2.7/dist-packages/dns/update.py", line 116, in _add
    self.origin)
  File "/usr/lib/python2.7/dist-packages/dns/rdata.py", line 428, in from_text
    return cls.from_text(rdclass, rdtype, tok, origin, relativize)
  File "/usr/lib/python2.7/dist-packages/dns/rdtypes/IN/A.py", line 44, in from_text
    return cls(rdclass, rdtype, address)
  File "/usr/lib/python2.7/dist-packages/dns/rdtypes/IN/A.py", line 34, in __init__
    dns.ipv4.inet_aton(address)
  File "/usr/lib/python2.7/dist-packages/dns/ipv4.py", line 51, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

**Comment by aroth-arsoft** [comment]
old version of the script
